package dev.objz.commandbridge.net.proto;

public enum MessageType {
    AUTH_REQUEST, AUTH_OK, AUTH_FAIL, 
    REGISTER_COMMANDS,
    REGISTER_COMMANDS_RESULT,
    INVOKED_COMMAND,
    EXECUTE_COMMAND,
    EXECUTE_COMMAND_RESULT,
    SCHEDULE_LISTENER,
    PLAYER_LIST,
    PLAYER_JOIN,
    PLAYER_LEAVE,
    PING, PONG,
    RESOLVE_UUID, RESOLVE_UUID_RESPONSE,
    DUMP_REQUEST, DUMP_RESPONSE
}
