plugins {
    `java-library`
    `checkstyle`
}

java {
    toolchain { languageVersion.set(JavaLanguageVersion.of(21)) }
    withSourcesJar()
}

repositories {
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/")
    maven("https://repo.william278.net/releases/")
    maven("https://repo.codemc.io/repository/maven-releases/")
    maven("https://repo.codemc.io/repository/maven-snapshots/")
}

dependencies {
    implementation(project(":api"))
    implementation(project(":core"))
    implementation("redis.clients:jedis:7.1.0")

    compileOnly("com.velocitypowered:velocity-api:3.4.0-SNAPSHOT")
    annotationProcessor("com.velocitypowered:velocity-api:3.4.0-SNAPSHOT")

    compileOnly("net.kyori:adventure-text-minimessage:4.17.0")
    compileOnly("net.kyori:adventure-api:4.17.0")

    compileOnly("org.spongepowered:configurate-yaml:4.2.0")
    compileOnly("org.spongepowered:configurate-core:4.2.0")
    compileOnly("dev.jorel:commandapi-velocity-core:11.2.0")

    compileOnly("org.bstats:bstats-velocity:3.2.0")


    compileOnly("net.william278:papiproxybridge:1.8.4")

    compileOnly("com.github.retrooper:packetevents-velocity:2.11.2")

    testImplementation(libs.junit.jupiter)
    testImplementation("com.velocitypowered:velocity-api:3.4.0-SNAPSHOT")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

tasks.test {
    useJUnitPlatform()
}

tasks.jar {
    // velocity-plugin.json exists in src/main/resources (with @version@ placeholder)
    // and is also generated by the annotation processor. The dist module handles
    // version replacement and packaging, so exclude it from the velocity jar.
    exclude("velocity-plugin.json")
}
