name: CommandBridge
version: 2.2.9
main: dev.objz.commandbridge.paper.Main
author: objz
api-version: '1.20'
folia-supported: true
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
